jobs:
  - job: Run_tflint
    steps:
    - checkout: self
    - task: CmdLine@2
      inputs: 
        script: |
          echo Curl tflint_config_file

          wget -P $(Agent.BuildDirectory) https://raw.githubusercontent.com/qbeyond/terraform-tests/feature/init/.tflint.hcl
    - task: CmdLine@2
      inputs:
        script: |
          echo Look for tflint config

          cd $(Agent.BuildDirectory)
          ls
    - task: CmdLine@2
      inputs: 
        script: |
          echo Curl tflint

          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
    - task: CmdLine@2
      inputs:
        script: |
          echo init tflints

          tflint --init
    - task: CmdLine@2
      inputs:
        script: |
          echo start tflint

          tflint --recursive